### ISSUE TITLE
Will add WireGuard Support？

### ISSUE THREAD

**Issue by yorfir** [MeowLove/OpenWRT-Virtualization-Servers#1]
In the future

**Comment by MeowLove** [comment]
Hello, as the basic OpenWRT framework, this firmware has enough space to allow users to install their own software. 

Please install the software you need by yourself. To install WireGuard, it is very simple, you can:

1. read the official OpenWRT document:
https://openwrt.org/docs/guide-user/services/vpn/wireguard/basics
2. Search for "OpenWRT install WireGuard" through Google Search:
https://www.google.com/search?q=OpenWRT+install+WireGuard

================================================

你好，本固件作为基本的OpenWRT框架，具有足够的空间允许用户安装自己的软件。

请自行安装你需要的软件。想要安装WireGuard，这非常简单，你可以：

1、阅读OpenWRT官方文档：
https://openwrt.org/docs/guide-user/services/vpn/wireguard/basics
2、通过谷歌搜索“OpenWRT install WireGuard”：
https://www.google.com/search?q=OpenWRT+install+WireGuard
